### ISSUE TITLE
【报告问题】图标显示不全

### ISSUE THREAD

**Issue by Anz-03** [MSEDGE-CORE/Edge18#1]
描述问题：

如何复现：

期望样式：

屏幕截图：
![image](https://github.com/MSEDGE-CORE/Edge18/assets/106299500/7fdd4a16-444f-44f1-84b3-e00508795630)

系统版本：windows10

附加备注：

**Comment by MSEDGE-CORE** [comment]
请自行安装 Segoe Fluent Icons 字体
https://aka.ms/SegoeFluentIcons
