### ISSUE TITLE
【报告问题】应用内的各种图标无法显示

### ISSUE THREAD

**Issue by SuanOrange** [MSEDGE-CORE/Edge18#14]
描述问题：应用内的各种图标无法显示

如何复现：在WIN10系统下打开应用

期望样式：正常显示图标

屏幕截图：
![屏幕截图 2024-08-15 110644](https://github.com/user-attachments/assets/19952d1c-d98a-4c64-8380-6a1e21618796)

系统版本：Windows 10 22H2 19045.4717

附加备注：

**Comment by MSEDGE-WXZ** [comment]
请安装 Segoe Fluent Icons 字体
https://aka.ms/SegoeFluentIcons
