### ISSUE TITLE
【报告问题】进入设置时不会自动关闭下载窗口

### ISSUE THREAD

**Issue by MSEDGE-WXZ** [MSEDGE-CORE/Edge18#2]
描述问题：
1. 进入设置时不会自动关闭下载窗口

如何复现：
1. 点击下载按钮
2. 点击设置

期望样式：
1. 下载窗口自动关闭

屏幕截图：
![屏幕截图 2023-12-23 162010](https://github.com/MSEDGE-CORE/Edge18/assets/154116904/f21b9619-faae-4db2-befb-d73f7100d84e)

**Comment by MSEDGE-CORE** [comment]
将在下个版本修复。

**Comment by MSEDGE-CORE** [comment]
将在下个版本修复。
