### ISSUE TITLE
【报告问题】

### ISSUE THREAD

**Issue by xubinyu233** [MSEDGE-CORE/Edge18#7]
描述问题：打开edge18字体不完全

如何复现：打开后

期望样式：恢复正常

屏幕截图：
![屏幕截图 2024-05-31 182110](https://github.com/MSEDGE-CORE/Edge18/assets/171336538/b0d9efe7-336d-4cd0-854a-73e11ab23dae)

系统版本：win10 22h2 19045.4412

附加备注：无

**Comment by MSEDGE-CORE** [comment]
https://aka.ms/SegoeFluentIcons
