### ISSUE TITLE
【报告问题】几个 bugs

### ISSUE THREAD

**Issue by Uevo001** [MSEDGE-CORE/Edge18#9]
**描述问题：**

1、当打开一个网页后，再点击地址栏，内网址没有被全选
2、Chromium 内核打开一个页面后，无法滚动网页，必须先切换到另一个网页后再切换回来，才可以滚动
3、Chromium 内核重启后（如在edge://flags中调整），整个程序会卡死然后直接崩溃退出
4、使用 Clash Verge 代理时，如选系统代理，则任何网页都无法访问，不管有没有被墙，貌似直接无法连接到网络（和 Microsoft Store 相似）；若选 Tun 模式，即使选了全局代理，也只能访问没有被墙的网站
5、浏览器中常见的快捷键，如 Ctrl + H 打开历史记录， Ctrl + J 打开下载管理页面等，都没有体现
6、无法自定义下载的保存路径
7、地址栏只能输入网址，无法像搜索框一样可以搜索内容

**如何复现：**

2、4 怀疑是个例，不知道能不能稳定复现

**期望样式：**

如上

**屏幕截图：**

None

**系统版本：**

Windows 11 24H2 10.0.26100.863

**附加备注：**

很好的项目，特别赞的是有EdgeHTML支持，再完善一下就更好了

**Comment by MSEDGE-CORE** [comment]
试着改一下，估计要过几年才能完工（bushi
